### ISSUE TITLE
New font for body of text in app.

### ISSUE THREAD

**Issue by tedbjurlin** [DiscoTrayStudios/lake-nixon-scheduling#126]
**Is your feature request related to a problem? Please describe.**
The current font is fine for titles and headers but is difficult to read when the text is smaller.

**Describe the solution you'd like**
We should find and implement a new font for the rest of the text in the app. This can be added to the textStyles in the theme.

**Comment by mgoadric** [comment]
FontJoy might be a nice way to find good font pairings for this app https://fontjoy.com/

**Comment by tedbjurlin** [comment]
Gotcha
