### ISSUE TITLE
changing Circle Avatar letters to animals

### ISSUE THREAD

**Issue by Larsonog** [DiscoTrayStudios/lake-nixon-scheduling#5]

**Comment by tedbjurlin** [comment]
**Is your feature request related to a problem? Please describe.**
Avatars for groups are not useful indications of which group they represent.

**Describe the solution you'd like**
Changing the avatars to images of the animal they are named after would fix this issue.

**Describe alternatives you've considered**
Removing the icons altogether is also an option, but it would be better to keep them.

**Comment by tedbjurlin** [comment]
Removed icons on groups page
